sudo: required

services:
  - docker

before_install:
  # Show current processes using port 5432
  - sudo lsof -i :5432
  # Update `docker-ce`
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce=${DOCKER_CE_DPKG_VERSION}
  # Install `docker-compose`
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Run `docker-compose`
  - sudo docker-compose up -d
  - docker ps -a
