version: '3'

services:
  api:
    depends_on:
      - database
    image: tiangolo/uwsgi-nginx-flask:python3.6
    volumes:
      - ./api:/app
    working_dir: /app
    environment:
      - VIRTUAL_HOST=${API_VIRTUAL_HOST}

  database:
    image: postgres:${POSTGRES_IMAGE_VERSION}
    volumes:
      - database_data:${POSTGRES_PGDATA}
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=${POSTGRES_PGDATA}
      - VIRTUAL_HOST=${DATABASE_VIRTUAL_HOST}

  proxy:
    image: jwilder/nginx-proxy:${NGINX_IMAGE_VERSION}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    ports:
      - "80:80"

volumes:
  database_data: {}
